### ISSUE TITLE
Remove Sidebar from  Docs

### ISSUE THREAD

**Issue by mundume** [nzaih1999/atomize_icons#9]
Description: The current atomize docs website includes a sidebar, which can be distracting and takes up valuable screen space. A I would like to suggest removing the sidebar to create a cleaner and more focused documentation layout. This change will improve the overall user experience and make it easier to read and navigate the documentation.

**Comment by ThaungThanHan** [comment]
Hello. I will work on it. Please assign it to me.

**Comment by mundume** [comment]
@ThaungThanHan  done [here is the website repo](https://github.com/nzaih1999/atomize-icons-website)

**Comment by ThaungThanHan** [comment]
Hello, @nzaih1999 . As far as I have read through the documentation, Nextra does not provide feature to remove the sidebar but a toggle to hide/show the sidebar. The sidebar always show upon the app starts and haven't found the option to keep it hidden at the page start without the need to toggle it by clicking it.

**Comment by mundume** [comment]
@ThaungThanHan  sorry for the inconvinience. I didnt read through the docs well. But you can work on some other stuff like working on the about page

**Comment by mundume** [comment]
> @ThaungThanHan sorry for the inconvinience. I didnt read through the docs well. But you can work on some other stuff like working on the about page

you can open an issue for it

**Comment by ThaungThanHan** [comment]
> @ThaungThanHan sorry for the inconvinience. I didnt read through the docs well. But you can work on some other stuff like working on the about page

No worries, @nzaih1999 . I will check on the about page. And do you need me to make PR for sidebar toggle?

**Comment by mundume** [comment]
No I think we should leave it like that..there is another project I'm working on we'll utilize nextra to the fullest

**Comment by ThaungThanHan** [comment]
Sure, thanks. You can close this issue now. I will move on to About page.

**Comment by mundume** [comment]
thanks man..I'll close the issue you can open the issue on the about page on the website repo
